// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/lsd.proto

package lsd

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotificationPayload struct {
	To                   []string      `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Notification         *Notification `protobuf:"bytes,2,opt,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NotificationPayload) Reset()         { *m = NotificationPayload{} }
func (m *NotificationPayload) String() string { return proto.CompactTextString(m) }
func (*NotificationPayload) ProtoMessage()    {}
func (*NotificationPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca3cecd9ea5e5eb, []int{0}
}

func (m *NotificationPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationPayload.Unmarshal(m, b)
}
func (m *NotificationPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationPayload.Marshal(b, m, deterministic)
}
func (m *NotificationPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationPayload.Merge(m, src)
}
func (m *NotificationPayload) XXX_Size() int {
	return xxx_messageInfo_NotificationPayload.Size(m)
}
func (m *NotificationPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationPayload.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationPayload proto.InternalMessageInfo

func (m *NotificationPayload) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *NotificationPayload) GetNotification() *Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

type NotificationResult struct {
	Ok                   bool              `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Notifications        map[string]string `protobuf:"bytes,2,rep,name=notifications,proto3" json:"notifications,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NotificationResult) Reset()         { *m = NotificationResult{} }
func (m *NotificationResult) String() string { return proto.CompactTextString(m) }
func (*NotificationResult) ProtoMessage()    {}
func (*NotificationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca3cecd9ea5e5eb, []int{1}
}

func (m *NotificationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationResult.Unmarshal(m, b)
}
func (m *NotificationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationResult.Marshal(b, m, deterministic)
}
func (m *NotificationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationResult.Merge(m, src)
}
func (m *NotificationResult) XXX_Size() int {
	return xxx_messageInfo_NotificationResult.Size(m)
}
func (m *NotificationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationResult.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationResult proto.InternalMessageInfo

func (m *NotificationResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *NotificationResult) GetNotifications() map[string]string {
	if m != nil {
		return m.Notifications
	}
	return nil
}

type Notification struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Options              []string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca3cecd9ea5e5eb, []int{2}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Notification) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Notification) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

type NewTokenPayload struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTokenPayload) Reset()         { *m = NewTokenPayload{} }
func (m *NewTokenPayload) String() string { return proto.CompactTextString(m) }
func (*NewTokenPayload) ProtoMessage()    {}
func (*NewTokenPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca3cecd9ea5e5eb, []int{3}
}

func (m *NewTokenPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTokenPayload.Unmarshal(m, b)
}
func (m *NewTokenPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTokenPayload.Marshal(b, m, deterministic)
}
func (m *NewTokenPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTokenPayload.Merge(m, src)
}
func (m *NewTokenPayload) XXX_Size() int {
	return xxx_messageInfo_NewTokenPayload.Size(m)
}
func (m *NewTokenPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTokenPayload.DiscardUnknown(m)
}

var xxx_messageInfo_NewTokenPayload proto.InternalMessageInfo

func (m *NewTokenPayload) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type TokenPayload struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenPayload) Reset()         { *m = TokenPayload{} }
func (m *TokenPayload) String() string { return proto.CompactTextString(m) }
func (*TokenPayload) ProtoMessage()    {}
func (*TokenPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca3cecd9ea5e5eb, []int{4}
}

func (m *TokenPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenPayload.Unmarshal(m, b)
}
func (m *TokenPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenPayload.Marshal(b, m, deterministic)
}
func (m *TokenPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenPayload.Merge(m, src)
}
func (m *TokenPayload) XXX_Size() int {
	return xxx_messageInfo_TokenPayload.Size(m)
}
func (m *TokenPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenPayload.DiscardUnknown(m)
}

var xxx_messageInfo_TokenPayload proto.InternalMessageInfo

func (m *TokenPayload) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type TokenResult struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResult) Reset()         { *m = TokenResult{} }
func (m *TokenResult) String() string { return proto.CompactTextString(m) }
func (*TokenResult) ProtoMessage()    {}
func (*TokenResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca3cecd9ea5e5eb, []int{5}
}

func (m *TokenResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResult.Unmarshal(m, b)
}
func (m *TokenResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResult.Marshal(b, m, deterministic)
}
func (m *TokenResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResult.Merge(m, src)
}
func (m *TokenResult) XXX_Size() int {
	return xxx_messageInfo_TokenResult.Size(m)
}
func (m *TokenResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResult.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResult proto.InternalMessageInfo

func (m *TokenResult) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *TokenResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*NotificationPayload)(nil), "lsd.NotificationPayload")
	proto.RegisterType((*NotificationResult)(nil), "lsd.NotificationResult")
	proto.RegisterMapType((map[string]string)(nil), "lsd.NotificationResult.NotificationsEntry")
	proto.RegisterType((*Notification)(nil), "lsd.Notification")
	proto.RegisterType((*NewTokenPayload)(nil), "lsd.NewTokenPayload")
	proto.RegisterType((*TokenPayload)(nil), "lsd.TokenPayload")
	proto.RegisterType((*TokenResult)(nil), "lsd.TokenResult")
}

func init() { proto.RegisterFile("proto/lsd.proto", fileDescriptor_9ca3cecd9ea5e5eb) }

var fileDescriptor_9ca3cecd9ea5e5eb = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x25, 0xc9, 0xf7, 0xd5, 0x76, 0x5a, 0x6d, 0x3b, 0x16, 0x1b, 0x7a, 0x0a, 0x39, 0x48, 0xf4,
	0xd0, 0x42, 0x45, 0x10, 0xbd, 0x28, 0xb4, 0x16, 0x41, 0x4a, 0xd9, 0xea, 0xcd, 0x4b, 0x6a, 0x56,
	0x08, 0x09, 0x99, 0x92, 0xdd, 0x2a, 0xf9, 0x67, 0x1e, 0xfd, 0x69, 0x92, 0x4d, 0xaa, 0x59, 0x4a,
	0xc1, 0xdb, 0xbc, 0xd9, 0xf7, 0xde, 0xcc, 0x9b, 0x04, 0xda, 0xeb, 0x94, 0x24, 0x8d, 0x62, 0x11,
	0x0c, 0x55, 0x85, 0x56, 0x2c, 0x02, 0xf7, 0x05, 0x8e, 0xe7, 0x24, 0xc3, 0xb7, 0xf0, 0xd5, 0x97,
	0x21, 0x25, 0x0b, 0x3f, 0x8b, 0xc9, 0x0f, 0xf0, 0x08, 0x4c, 0x49, 0xb6, 0xe1, 0x58, 0x5e, 0x83,
	0x99, 0x92, 0xf0, 0x12, 0x5a, 0x49, 0x85, 0x66, 0x9b, 0x8e, 0xe1, 0x35, 0xc7, 0xdd, 0x61, 0xee,
	0x56, 0xd5, 0x33, 0x8d, 0xe6, 0x7e, 0x1a, 0x80, 0xda, 0x33, 0x17, 0x9b, 0x58, 0xe6, 0xee, 0x14,
	0xd9, 0x86, 0x63, 0x78, 0x75, 0x66, 0x52, 0x84, 0x0b, 0x38, 0xac, 0xca, 0x84, 0x6d, 0x3a, 0x96,
	0xd7, 0x1c, 0x9f, 0xef, 0xda, 0x2b, 0xbd, 0xd6, 0x12, 0xd3, 0x44, 0xa6, 0x19, 0xd3, 0x0d, 0x06,
	0xb7, 0xfa, 0xdc, 0x82, 0x84, 0x1d, 0xb0, 0x22, 0x9e, 0xa9, 0xc1, 0x0d, 0x96, 0x97, 0xd8, 0x83,
	0xff, 0xef, 0x7e, 0xbc, 0xe1, 0x2a, 0x50, 0x83, 0x15, 0xe0, 0xda, 0xbc, 0x32, 0x5c, 0x06, 0xad,
	0xaa, 0x43, 0xce, 0x94, 0xa1, 0x8c, 0x79, 0xa9, 0x2e, 0x00, 0x22, 0xfc, 0x5b, 0x51, 0x90, 0x95,
	0x72, 0x55, 0xa3, 0x0d, 0x07, 0xb4, 0x2e, 0x72, 0x58, 0xea, 0x80, 0x5b, 0xe8, 0x9e, 0x41, 0x7b,
	0xce, 0x3f, 0x9e, 0x28, 0xe2, 0x3f, 0x87, 0x3e, 0x81, 0xda, 0x46, 0xf0, 0xf4, 0x61, 0x52, 0xfa,
	0x96, 0xc8, 0x3d, 0x85, 0xd6, 0x9f, 0x78, 0x37, 0xd0, 0x54, 0xbc, 0xf2, 0xb2, 0x7b, 0x68, 0x6a,
	0xfb, 0x9c, 0xb6, 0xcd, 0xa9, 0xc0, 0xf8, 0xcb, 0x00, 0xeb, 0x71, 0x39, 0xc1, 0x29, 0x74, 0x96,
	0x3c, 0x09, 0xb4, 0xbc, 0xf6, 0xce, 0xf1, 0xcb, 0x55, 0x06, 0xfd, 0x3d, 0x9f, 0x05, 0xef, 0xa0,
	0x3f, 0xe3, 0x09, 0x4f, 0x7d, 0xc9, 0xb7, 0x31, 0xef, 0x29, 0x7d, 0x16, 0x3c, 0xc5, 0x5e, 0xa1,
	0xd1, 0xc3, 0x0f, 0x3a, 0xaa, 0x5b, 0xdd, 0x7f, 0x04, 0xf5, 0x19, 0x97, 0xaa, 0x83, 0xdd, 0xdf,
	0xd7, 0xbd, 0x82, 0x55, 0x4d, 0xfd, 0xcb, 0x17, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xa7,
	0xf4, 0x07, 0xde, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LSDClient is the client API for LSD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LSDClient interface {
	SendNotification(ctx context.Context, in *NotificationPayload, opts ...grpc.CallOption) (*NotificationResult, error)
	//    rpc GenerateNewKeyPair(NewKeyPairPayload) returns (KeyPairResult);
	GenerateNewTokenForUser(ctx context.Context, in *NewTokenPayload, opts ...grpc.CallOption) (*TokenResult, error)
	//    rpc GetKeyPair(KeyPairPayload) returns (KeyPairResult);
	GetToken(ctx context.Context, in *TokenPayload, opts ...grpc.CallOption) (*TokenResult, error)
}

type lSDClient struct {
	cc *grpc.ClientConn
}

func NewLSDClient(cc *grpc.ClientConn) LSDClient {
	return &lSDClient{cc}
}

func (c *lSDClient) SendNotification(ctx context.Context, in *NotificationPayload, opts ...grpc.CallOption) (*NotificationResult, error) {
	out := new(NotificationResult)
	err := c.cc.Invoke(ctx, "/lsd.LSD/SendNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lSDClient) GenerateNewTokenForUser(ctx context.Context, in *NewTokenPayload, opts ...grpc.CallOption) (*TokenResult, error) {
	out := new(TokenResult)
	err := c.cc.Invoke(ctx, "/lsd.LSD/GenerateNewTokenForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lSDClient) GetToken(ctx context.Context, in *TokenPayload, opts ...grpc.CallOption) (*TokenResult, error) {
	out := new(TokenResult)
	err := c.cc.Invoke(ctx, "/lsd.LSD/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LSDServer is the server API for LSD service.
type LSDServer interface {
	SendNotification(context.Context, *NotificationPayload) (*NotificationResult, error)
	//    rpc GenerateNewKeyPair(NewKeyPairPayload) returns (KeyPairResult);
	GenerateNewTokenForUser(context.Context, *NewTokenPayload) (*TokenResult, error)
	//    rpc GetKeyPair(KeyPairPayload) returns (KeyPairResult);
	GetToken(context.Context, *TokenPayload) (*TokenResult, error)
}

// UnimplementedLSDServer can be embedded to have forward compatible implementations.
type UnimplementedLSDServer struct {
}

func (*UnimplementedLSDServer) SendNotification(ctx context.Context, req *NotificationPayload) (*NotificationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotification not implemented")
}
func (*UnimplementedLSDServer) GenerateNewTokenForUser(ctx context.Context, req *NewTokenPayload) (*TokenResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateNewTokenForUser not implemented")
}
func (*UnimplementedLSDServer) GetToken(ctx context.Context, req *TokenPayload) (*TokenResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}

func RegisterLSDServer(s *grpc.Server, srv LSDServer) {
	s.RegisterService(&_LSD_serviceDesc, srv)
}

func _LSD_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LSDServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lsd.LSD/SendNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LSDServer).SendNotification(ctx, req.(*NotificationPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _LSD_GenerateNewTokenForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTokenPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LSDServer).GenerateNewTokenForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lsd.LSD/GenerateNewTokenForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LSDServer).GenerateNewTokenForUser(ctx, req.(*NewTokenPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _LSD_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LSDServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lsd.LSD/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LSDServer).GetToken(ctx, req.(*TokenPayload))
	}
	return interceptor(ctx, in, info, handler)
}

var _LSD_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lsd.LSD",
	HandlerType: (*LSDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotification",
			Handler:    _LSD_SendNotification_Handler,
		},
		{
			MethodName: "GenerateNewTokenForUser",
			Handler:    _LSD_GenerateNewTokenForUser_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _LSD_GetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lsd.proto",
}
